spring.application.name=Weather_api
# ---- Server ----
server.port=8080

# ---- MySQL ----
spring.datasource.url=jdbc:mysql://localhost:3306/weatherdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Example@2022#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ---- JPA/Hibernate ----
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ---- OpenWeather ----
openweather.base-url=https://api.openweathermap.org
openweather.api-key=71f09ee06da4bcd0bf5fd338da39a910
openweather.units=metric
